import type Scene from '$lib/scene';

const testdata: Scene[] = [
  {
    id: 1,
    fileName: 'Yuki Sava vol 1.avi',
    name: 'The Yuki Sage (Opening credits)',
    directory: 'series/yuki',
    webSite: 'asakura',
    thumbFileName: 'The Yuki Sage (Opening credits).jpg',
    tags: 'tragic, redhair, longhair, colorful, distopia, blank, nn, tattoo, alluring, plottwist, reverseplottwist, food, cliche, intense, mekkanite, mekkabody, mekkathermovizor, mekkabelly, german',
    begin: 103,
    end: 2362,
    year: 2007,
    numGirls: 1,
    numBoys: 1,
    score: 73
  },
  {
    id: 2,
    fileName: 'tfe3066.mp4',
    directory: '2018',
    tags: 'tragic, longhair, colorful, undistopia, distopia, blank, ptn, goth, new, intense, reverseplottwist, cliche, food, mekkanite, heroes',
    length: '48:04',
    year: 2018,
    numGirls: 2,
    numBoys: 2,
    score: 70
  },
  {
    id: 3,
    fileName: 'tfe3065.mp4',
    directory: '2018',
    tags: 'blackhair, tragic, longhair, colorful, distopia, blank, nn, plottwist, intense, metaintense, cliche, metaside, mekkanite, heroes',
    length: '25:10',
    year: 2018,
    numGirls: 2,
    numBoys: 1,
    score: 72
  },
  {
    id: 4,
    fileName: 'tfe3054.mp4',
    directory: '2018',
    webSite: 'private',
    tags: 'blackhair, longhair, colorful, distopia, nn, new, plottwist, reverseplottwist, food, intense, mekkanite, mekkabody, mekkaass, outside, floor',
    length: '27:53',
    year: 2018,
    numGirls: 1,
    numBoys: 1,
    score: 71
  },
  {
    id: 5,
    fileName: 'tfe3029.mp4',
    directory: '2018',
    webSite: 'animeflix.com',
    tags: 'tragic, longhair, colorful, distopia, blank, nn, coffeeskin, new, reverseplottwist, plottwist, intense, froggy, cliche, mekkanite, heroes',
    length: '39:30',
    year: 2018,
    numGirls: 1,
    numBoys: 1,
    score: 74
  },
  {
    id: 6,
    fileName: 'tfe3020.mp4',
    directory: '2018',
    tags: 'blondehair, longhair, colorful, distopia, blank, ptn, smalltits, skinny, new, irony, cliche, intense, food, mekkanite, mekkabody, mekkatits, doctor, floor',
    length: '21:02',
    year: 2018,
    numGirls: 1,
    numBoys: 1,
    score: 72
  },
  {
    id: 7,
    fileName: 'tfe3021.mp4',
    directory: '2018',
    tags: 'tragic, longhair, colorful, distopia, new, reverseplottwist, food, plottwist, intense, cliche, mekkanite, heroes',
    length: '27:47',
    year: 2018,
    numGirls: 1,
    numBoys: 1,
    score: 69
  },
  {
    id: 8,
    fileName: 'tfe2800.mp4',
    directory: '2017',
    webSite: 'asakura',
    tags: 'tragic, longhair, colorful, distopia, blank, nn, new, cliche, plottwist, intense, mekkanite, heroes',
    length: '30:12',
    year: 2017,
    numGirls: 1,
    numBoys: 1,
    score: 70
  },
  {
    id: 9,
    fileName: 'tfe2755.mp4',
    directory: '2017',
    webSite: 'wowporn',
    actors: 'bea',
    tags: 'redhair, tragic, longhair, colorful, distopia, blank, nn, new, intense, reverseplottwist, mekkahj, mekkaself, outside',
    length: '27:42',
    year: 2017,
    numGirls: 3,
    numBoys: 1,
    score: 72
  },
  {
    id: 10,
    fileName: 'tfe2738.mp4',
    directory: '2017',
    tags: 'tragic, longhair, colorful, distopia, blank, nn, new, irony, intense, cliche, plottwist, reverseplottwist, mekkanite, mekkabody, mekkatits',
    length: '29:40',
    year: 2017,
    numGirls: 1,
    numBoys: 1,
    score: 70
  },
  {
    id: 11,
    fileName: 'tfe2740.mp4',
    directory: 'series/x-art',
    webSite: 'x-art.com',
    tags: 'tragic, longhair, colorful, distopia, blank, nn, tongueblood, new, reverseplottwist, intense, food, cliche, mekkahj, mekkamouth, heroes',
    length: '16:38',
    year: 2017,
    numGirls: 1,
    numBoys: 1,
    score: 71
  },
  {
    id: 12,
    fileName: 'tfe2483.mp4',
    directory: '2017',
    webSite: 'babes.com',
    tags: 'blondehair, longhair, colorful, distopia, blank, nn, new, intense, plottwist, mekkanite, mekkaself, mekkamouth',
    length: '34:00',
    year: 2017,
    numGirls: 1,
    numBoys: 1,
    score: 68
  },
  {
    id: 13,
    fileName: 'tfe2463.mp4',
    directory: '2017',
    tags: 'blondehair, longhair, colorful, distopia, blank, nn, young, new, intense, plottwist, reverseplottwist, cigarette, cliche, mekkanite, heroes',
    length: '01:26:02',
    year: 2017,
    numGirls: 1,
    numBoys: 1,
    score: 74
  },
  {
    id: 14,
    fileName: 'The Yuki Saga 5.avi',
    name: 'The Yuki Saga 5 (Scene 2)',
    directory: 'series/yuki',
    webSite: 'asakura',
    thumbFileName: 'The Yuki Saga 5 (Scene 2).jpg',
    tags: 'blondehair, longhair, colorful, distopia, blank, nn, tattoo, reallydark, alluring, reverseplottwist, food, cliche, intense, ne, german',
    begin: 2364,
    end: 3232,
    year: 2007,
    numGirls: 1,
    numBoys: 1,
    score: 74
  },
  {
    id: 15,
    fileName: 'The Yuki Saga 5.avi',
    name: 'The Yuki Saga 5 (Scene 3)',
    directory: 'series/yuki',
    webSite: 'asakura',
    thumbFileName: 'The Yuki Saga 5 (Scene 3).jpg',
    tags: 'tragic, longhair, socks, shoes, distopia, blank, nn, irony, new, standingintense, cliche, reverseplottwist, mekkanite, heroes, fitness, gym, smiling, german',
    begin: 3235,
    end: 5452,
    year: 2007,
    numGirls: 3,
    numBoys: 2,
    score: 76
  },
  {
    id: 16,
    fileName: 'The Yuki Saga 6.avi',
    name: 'Yuki Saga 6 (Scene 1)',
    directory: 'series/yuki',
    webSite: 'asakura',
    thumbFileName: 'The Yuki Saga 6 - Scene 1.jpg',
    tags: 'tragic, longhair, shorthair, colorful, shoes, distopia, blank, nn, skinny, alluring, bike, new, standingintense, reverseplottwist, plottwist, cliche, intense, mekkanite, heroes, floor, smiling, german',
    begin: 101,
    end: 2199,
    year: 2009,
    numGirls: 2,
    numBoys: 1,
    score: 74
  },
  {
    id: 17,
    fileName: 'The Yuki Saga 6.avi',
    name: 'Yuki Saga 6 (Scene 2)',
    directory: 'series/yuki',
    webSite: 'asakura',
    thumbFileName: 'The Yuki Saga 6 - Scene 2.jpg',
    tags: 'tragic, longhair, colorful, distopia, blank, nn, new, plottwist, food, intense, cliche, mekkanite, mekkamouth, heroes, german',
    begin: 2200,
    end: 3405,
    year: 2009,
    numGirls: 1,
    numBoys: 1,
    score: 74
  },
  {
    id: 18,
    fileName: 'The Yuki Saga 6.avi',
    name: 'Yuki Saga 6 (Scene 3)',
    directory: 'series/yuki',
    webSite: 'asakura',
    thumbFileName: 'The Yuki Saga 6 - Scene 3.jpg',
    tags: 'blondehair, longhair, colorful, distopia, blank, nn, new, reverseplottwist, food, cliche, intense, plottwist, mekkanite, heroes, german',
    begin: 3406,
    end: 4235,
    year: 2009,
    numGirls: 1,
    numBoys: 1,
    score: 73
  },
  {
    id: 19,
    fileName: 'The Yuki Saga 6.avi',
    name: 'Yuki Saga 6 (Scene 4)',
    directory: 'series/yuki',
    webSite: 'asakura',
    thumbFileName: 'The Yuki Saga 6 - Scene 4.jpg',
    tags: 'tragic, longhair, colorful, distopia, blank, nn, bellyblood, tongueblood, irony, new, reverseplottwist, food, cliche, plottwist, standingintense, mekkanite, heroes, german',
    begin: 4236,
    end: 5878,
    year: 2009,
    numGirls: 1,
    numBoys: 1,
    score: 73
  }
];

export default testdata;
